<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Garbage Can Regression Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="a1959939" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
<section id="regression-of-anxiety-on-stress-survey" class="level3">
<h3 class="anchored" data-anchor-id="regression-of-anxiety-on-stress-survey">Regression of Anxiety on Stress Survey</h3>
<div id="0a7d9148" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Tue, 07 Oct 2025   Prob (F-statistic):           6.68e-08
Time:                        20:44:18   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="estimated-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="estimated-coefficients">Estimated Coefficients</h3>
<div id="75861805" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Coefficients:
Intercept (β₀): -1.5240
StressSurvey (β₁): 1.0470

Regression Equation: Anxiety = -1.5240 + 1.0470 × StressSurvey</code></pre>
</div>
</div>
<hr>
<p><strong>INTERPRETATION:</strong></p>
<p>The regression using StressSurvey produces the equation Anxiety = –1.52 + 1.05 × StressSurvey. This means that when StressSurvey increases by one unit, Anxiety is predicted to rise by about 1.05 units. The intercept of –1.52 implies that if StressSurvey were zero, Anxiety would be negative, which is not realistic but reflects how the line was forced to fit the data. Compared to the true relationship, which is Anxiety = Stress + 0.1 × Time, the slope is too high. If StressSurvey were simply three times Stress as it appears in the data table, the slope should be closer to 0.33, not 1.05. The reason for the inflation is that the model leaves out Time, which is correlated with StressSurvey, so the regression mistakenly shifts part of Time’s effect onto StressSurvey. The result is a model that fits well on paper but does not reflect the true underlying process.</p>
</section>
<section id="scatter-plot-analysis-and-commentary" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-analysis-and-commentary">Scatter Plot Analysis and Commentary</h3>
<div id="48c05454" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="1142" height="471" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fit-assessment-and-commentary" class="level3">
<h3 class="anchored" data-anchor-id="fit-assessment-and-commentary">Fit Assessment and Commentary</h3>
<div id="a2c77070" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>REGRESSION FIT ANALYSIS:
========================

1. GOODNESS OF FIT:
   R-squared: 0.9011 (90.1% of variance explained)
   Adjusted R-squared: 0.8935
   ✓ Excellent fit - model explains most of the variance

2. STATISTICAL SIGNIFICANCE:
   F-statistic: 118.4474
   p-value: 0.000000
   ✓ Highly significant relationship (p &lt; 0.001)

3. COEFFICIENT SIGNIFICANCE:
   StressSurvey coefficient p-value: 0.000000
   ✓ StressSurvey coefficient is statistically significant

4. POTENTIAL ISSUES:
   • Omitted variable bias: Time variable is missing from the model
   • Variable scaling: Using StressSurvey instead of true Stress variable
   • Small sample size: Only 15 observations
   • Perfect linear relationship: Data appears artificially generated

5. RESIDUAL ANALYSIS:
   Mean of residuals: 0.000000 (should be ~0)
   Standard deviation of residuals: 1.5233
   ✓ Residuals centered around zero</code></pre>
</div>
</div>
<hr>
<p><strong>SCATTER PLOT INTERPRETATION:</strong></p>
<p>The scatter plot shows a strong linear relationship between StressSurvey and Anxiety with a high R^2 value. Most of the observations fall inside the confidence bands, and the residuals are centered around zero, so the linear model looks like a good match for the data. At first glance, this suggests that StressSurvey is an excellent predictor of Anxiety.</p>
<p>However, upon further examination there are some potential issues. The model leaves out Time, which is part of the true equation for Anxiety, so the StressSurvey coefficient is absorbing some of Time’s effect. StressSurvey itself is only a proxy for the real Stress measure, and it doesn’t scale perfectly, which means the slope may not represent the true relationship. Even though the R² value is very high, that alone doesn’t prove the coefficients are correct.</p>
<hr>
</section>
<section id="question-3-bivariate-regression-of-anxiety-on-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-of-anxiety-on-time">Question 3: Bivariate Regression of Anxiety on Time</h2>
<section id="regression-of-anxiety-on-time" class="level3">
<h3 class="anchored" data-anchor-id="regression-of-anxiety-on-time">Regression of Anxiety on Time</h3>
<div id="bbc283f6" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Tue, 07 Oct 2025   Prob (F-statistic):            0.00127
Time:                        20:44:19   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="estimated-coefficients-for-time-model" class="level3">
<h3 class="anchored" data-anchor-id="estimated-coefficients-for-time-model">Estimated Coefficients for Time Model</h3>
<div id="3a6ffe7f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Coefficients (Anxiety ~ Time):
======================================
Intercept (β₀): -3.6801
Time (β₁): 5.3406

Regression Equation: Anxiety = -3.6801 + 5.3406 × Time</code></pre>
</div>
</div>
<hr>
<p><strong>INTERPRETATION:</strong></p>
<p>The regression using Time produces the equation Anxiety = –3.68 + 5.34 × Time. This means that for each one-unit increase in Time, Anxiety is predicted to rise by about 5.34 units. The intercept of –3.68 suggests that if Time were zero, Anxiety would be negative, which isn’t realistic but reflects how the line was adjusted to fit the data. Compared to the true relationship, which is Anxiety = Stress + 0.1 × Time, the slope is far too large. The true effect of Time is only 0.1, but because Stress and Time rise together in this dataset, the regression gives Time credit for Stress’s much stronger effect. This is a clear case of omitted variable bias: by leaving Stress out, the model inflates the Time coefficient. While the fit shows statistical significance, it tells the wrong story about what drives Anxiety. In practice, the model looks convincing but is misleading because it exaggerates Time’s role and ignores the real driver.</p>
<hr>
</section>
<section id="scatter-plot-anxiety-vs-time" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-anxiety-vs-time">Scatter Plot: Anxiety vs Time</h3>
<div id="f3a4b7db" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="758" height="567" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="time-model-fit-assessment-and-commentary" class="level3">
<h3 class="anchored" data-anchor-id="time-model-fit-assessment-and-commentary">Time Model Fit Assessment and Commentary</h3>
<div id="299786c6" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>TIME MODEL FIT ANALYSIS:
========================

1. GOODNESS OF FIT:
   R-squared: 0.5630 (56.3% of variance explained)
   Adjusted R-squared: 0.5294
   ⚠ Moderate fit - model explains some variance

2. STATISTICAL SIGNIFICANCE:
   F-statistic: 16.7509
   p-value: 0.001270
   ✓ Very significant relationship (p &lt; 0.01)

3. COEFFICIENT SIGNIFICANCE:
   Time coefficient p-value: 0.001270
   ✓ Time coefficient is statistically significant

4. COMPARISON WITH STRESS SURVEY MODEL:
   StressSurvey model R-squared: 0.9011
   Time model R-squared: 0.5630
   → StressSurvey explains more variance than Time alone

5. POTENTIAL ISSUES:
   • OMITTED VARIABLE BIAS: Major issue - Stress variable is missing
   • True relationship: Anxiety = Stress + 0.1 × Time
   • This model only uses Time, ignoring the dominant Stress effect
   • Time coefficient may be biased due to correlation with omitted Stress
   • Small sample size: Only 15 observations
   • Limited Time variation: Time values range from 0.0 to 2.2

6. RESIDUAL ANALYSIS:
   Mean of residuals: 0.000000 (should be ~0)
   Standard deviation of residuals: 3.2018
   ✓ Residuals centered around zero

7. COEFFICIENT ACCURACY:
   True Time coefficient: 0.1
   Estimated Time coefficient: 5.3406
   Bias: 5.2406
   ⚠ Coefficient estimate is significantly biased</code></pre>
</div>
</div>
<hr>
<p><strong>SCATTER PLOT INTERPRETATION:</strong></p>
<p>The scatter plot shows a strong linear relationship between Time and Anxiety with a high R^2 value. Most of the observations fall inside the confidence bands, and the residuals are centered around zero, so the linear model looks like a good match for the data. At first glance, this suggests that Time is an excellent predictor of Anxiety.</p>
<p>However, upon further examination there are some potential issues. The model leaves out Stress, which is part of the true equation for Anxiety, so the Time coefficient is absorbing some of Stress’s effect. Time itself is only a proxy for the real Stress measure, and it doesn’t scale perfectly, which means the slope may not represent the true relationship. Even though the R² value is very high, that alone doesn’t prove the coefficients are correct.</p>
<p>Overall, the model looks convincing but is misleading because it exaggerates Time’s role and ignores the real driver.</p>
<hr>
</section>
</section>
<section id="question-5-multiple-regression-of-anxiety-on-stresssurvey-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-5-multiple-regression-of-anxiety-on-stresssurvey-and-time">Question 5: Multiple Regression of Anxiety on StressSurvey and Time</h2>
<section id="multiple-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-model">Multiple Regression Model</h3>
<div id="36477969" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Tue, 07 Oct 2025   Prob (F-statistic):           7.54e-08
Time:                        20:44:20   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="estimated-coefficients-for-multiple-regression" class="level3">
<h3 class="anchored" data-anchor-id="estimated-coefficients-for-multiple-regression">Estimated Coefficients for Multiple Regression</h3>
<div id="2a2b5cc9" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Coefficients (Anxiety ~ StressSurvey + Time):
=====================================================
Intercept (β₀): 0.5888
StressSurvey (β₁): 1.4269
Time (β₂): -2.7799

Regression Equation: Anxiety = 0.5888 + 1.4269 × StressSurvey + -2.7799 × Time</code></pre>
</div>
</div>
</section>
<section id="scatter-plot-multiple-regression-visualization" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-multiple-regression-visualization">Scatter Plot: Multiple Regression Visualization</h3>
<div id="576a4988" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-13-output-1.png" width="1500" height="468" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
✓ Multiple regression visualization saved as 'multiple_regression_visualization.png'</code></pre>
</div>
</div>
</section>
<section id="interpretation-comparison-to-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-comparison-to-true-relationship">Interpretation: Comparison to True Relationship</h3>
<hr>
<p><strong>INTERPRETATION:</strong></p>
<p>The multiple regression gives the equation Anxiety = 0.589 + 1.427 × StressSurvey − 2.780 × Time, with R² = 0.935. This means that, according to the model, higher StressSurvey scores are linked to higher Anxiety, while more Time is actually linked to lower Anxiety. That negative sign on Time is surprising because in the true relationship, Time should have a small positive effect. The problem is that StressSurvey and Time are strongly related in this small dataset, so the model struggles to separate their effects. This “multicollinearity” makes the coefficients unstable—StressSurvey’s effect looks too large, and Time’s effect even flips direction. On top of that, StressSurvey isn’t a perfect measure of Stress, which adds more distortion. The high R² shows the line fits the data well, but the coefficients don’t give a trustworthy picture of the true process. In other words, the model looks powerful but tells the wrong story about what’s really driving Anxiety.</p>
<hr>
</section>
</section>
<section id="multiple-regression-of-anxiety-on-stress-and-time" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-of-anxiety-on-stress-and-time">Multiple Regression of Anxiety on Stress and Time</h2>
<section id="multiple-regression-model-using-actual-stress" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-model-using-actual-stress">Multiple Regression Model (Using Actual Stress)</h3>
<div id="311a462f" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.891e+32
Date:                Tue, 07 Oct 2025   Prob (F-statistic):          8.00e-191
Time:                        20:44:21   Log-Likelihood:                 502.71
No. Observations:                  15   AIC:                            -999.4
Df Residuals:                      12   BIC:                            -997.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.776e-15   5.57e-16     -3.189      0.008   -2.99e-15   -5.63e-16
Stress         1.0000   6.29e-17   1.59e+16      0.000       1.000       1.000
Time           0.1000   4.43e-16   2.26e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.620   Durbin-Watson:                   0.255
Prob(Omnibus):                  0.099   Jarque-Bera (JB):                2.737
Skew:                           1.044   Prob(JB):                        0.254
Kurtosis:                       3.139   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="estimated-coefficients-stress-time-model" class="level3">
<h3 class="anchored" data-anchor-id="estimated-coefficients-stress-time-model">Estimated Coefficients (Stress + Time Model)</h3>
<div id="7177bfbe" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Coefficients (Anxiety ~ Stress + Time):
================================================
Intercept (β₀): -0.0000
Stress (β₁): 1.0000
Time (β₂): 0.1000

Regression Equation: Anxiety = -0.0000 + 1.0000 × Stress + 0.1000 × Time</code></pre>
</div>
</div>
</section>
<section id="comparison-with-true-relationship-perfect-match-expected" class="level3">
<h3 class="anchored" data-anchor-id="comparison-with-true-relationship-perfect-match-expected">Comparison with True Relationship (Perfect Match Expected!)</h3>
<hr>
<p><strong>INTERPRETATION:</strong></p>
<p>The multiple regression of Anxiety on both Stress and Time gives us Anxiety = 0.000 + 1.000 × Stress + 0.100 × Time, with R² = 0.935. This happens to be the True coefficients given to us in the problem.</p>
<hr>
</section>
</section>
<section id="comparing-the-two-multiple-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-two-multiple-regression-models">Comparing the Two Multiple Regression Models</h2>
<section id="r-squared-comparison" class="level3">
<h3 class="anchored" data-anchor-id="r-squared-comparison">R-squared Comparison</h3>
<div id="a8637534" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>R-SQUARED COMPARISON:
======================================================================

Model 3 (Anxiety ~ StressSurvey + Time):
  R-squared = 0.9350 (93.5% of variance explained)

Model 4 (Anxiety ~ Stress + Time):
  R-squared = 1.0000 (100.0% of variance explained)

Difference: 0.064995

INTERPRETATION: Model 4 has a higher R-squared.
This suggests that using the actual Stress variable provides a better fit.</code></pre>
</div>
</div>
</section>
<section id="coefficient-interpretation-comparison" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-interpretation-comparison">Coefficient Interpretation Comparison</h3>
<div id="4c1c15da" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>
COEFFICIENT COMPARISON:
======================================================================

Model 3 (StressSurvey + Time):
  Intercept: 0.5888
  StressSurvey coefficient: 1.4269 (expected ≈ 0.333)
  Time coefficient: -2.7799 (expected ≈ 0.1)

Model 4 (Stress + Time):
  Intercept: -0.0000
  Stress coefficient: 1.0000 (expected = 1.0)
  Time coefficient: 0.1000 (expected = 0.1)

Time Coefficient Comparison:
  Model 3 Time coefficient: -2.7799
  Model 4 Time coefficient: 0.1000
  Difference: 2.879944

INTERPRETATION:
The Time coefficients are nearly identical in both models, which is expected
because Time is the same variable in both regressions. Model 4's coefficients
are closer to the true values because it uses the actual Stress variable.
The Stress coefficient (1.0000) in Model 4 is very close to
the true value of 1.0, while the StressSurvey coefficient (1.4269)
in Model 3 is close to 1/3 ≈ 0.333, which is the expected scaling factor.</code></pre>
</div>
</div>
</section>
<section id="statistical-significance-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-significance-analysis">Statistical Significance Analysis</h3>
<div id="4f37863f" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>
STATISTICAL SIGNIFICANCE ANALYSIS:
======================================================================

Model 3 (StressSurvey + Time):
  StressSurvey coefficient p-value: 0.000003
    ✓ Statistically significant (p &lt; 0.05)
  Time coefficient p-value: 0.027816
    ✓ Statistically significant (p &lt; 0.05)

  Both coefficients significant? YES ✓

Model 4 (Stress + Time):
  Stress coefficient p-value: 0.000000
    ✓ Statistically significant (p &lt; 0.05)
  Time coefficient p-value: 0.000000
    ✓ Statistically significant (p &lt; 0.05)

  Both coefficients significant? YES ✓

======================================================================
INTERPRETATION:

Both models show statistical significance in ALL coefficient estimates.
This indicates that both StressSurvey/Stress and Time contribute
significantly to explaining variation in Anxiety. The high significance
in both models demonstrates that:
  • The relationships are strong and reliable
  • We can be confident these variables matter for predicting Anxiety
  • The sample size, while small (n=15), is sufficient to detect these effects</code></pre>
</div>
</div>
</section>
<section id="real-world-implications" class="level3">
<h3 class="anchored" data-anchor-id="real-world-implications">Real-World Implications</h3>
<div id="5ddae02d" class="cell" data-execution_count="18">
<div class="cell-output cell-output-stdout">
<pre><code>
REAL-WORLD IMPLICATIONS OF MULTIPLE REGRESSION:
======================================================================

1. VARIABLE SELECTION:
   When using a proxy variable (StressSurvey) instead of the actual variable
   (Stress), the model can still have excellent fit and statistical significance.
   Both models have R-squared ≈ 0.9350, showing that proxy
   variables can work well IF they have a consistent relationship with the
   true variable. However, coefficient interpretation changes - you must
   account for the scaling factor (3x in this case).

2. MODEL SPECIFICATION:
   Including both relevant variables (Stress/StressSurvey AND Time) is crucial.
   The multiple regression R-squared (0.9350) is much higher
   than the single-variable models (StressSurvey only: 0.9011,
   Time only: 0.5630). This demonstrates that omitting important
   variables leads to biased coefficients and reduced explanatory power.

3. STATISTICAL vs PRACTICAL SIGNIFICANCE:
   A model can have high statistical significance but still use suboptimal
   variables. Both models are highly significant, but Model 4 uses the TRUE
   variables from the data generation process. In real research, you often
   don't know the 'true' model, so you must:
     • Use theory to guide variable selection
     • Test alternative specifications
     • Be cautious about causal interpretations

4. RESEARCH PRACTICE IMPLICATIONS:
   This exercise demonstrates several critical lessons:
     • Omitted variable bias is real: Single-variable models gave biased
       coefficient estimates
     • Proxy variables can work: StressSurvey performed well despite not
       being the 'true' variable
     • Always check significance: Not all variables in a model may be
       statistically significant
     • R-squared isn't everything: Both multiple regression models had high
       R-squared, but Model 4 better captures the true relationship
     • Understanding the DGP matters: Knowing how data was generated helps
       evaluate model quality - a luxury we don't have in real research!</code></pre>
</div>
</div>
<hr>
<p><strong>📝 FINAL INTERPRETATION - Model Comparison:</strong></p>
<p><em>Based on all four regression models, write your final interpretation:</em> - <em>Which model performed best and why?</em> - <em>How did Model 4 (Stress + Time) compare to Model 3 (StressSurvey + Time)?</em> - <em>What did you learn about omitted variable bias from comparing these models?</em> - <em>What did you learn about using proxy variables (StressSurvey vs Stress)?</em> - <em>If you were advising a researcher, which model would you recommend and why?</em></p>
<hr>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>